### ISSUE TITLE
build Slope Script-KI

### ISSUE THREAD

**Issue by Andarix** [Dwachs/simutrans-scenarios#11]
r10674 (neuer noch nicht getestet)

Die Script-KI baut jetzt die falschen Slopes. Weis nicht wo der Fehler genau liegt. Es handelt sich um ein Serverspiel. Lokales Spiel noch nicht getestet.

Aus einem aktuellen Serverspiel.
![unknown](https://user-images.githubusercontent.com/63728326/187063113-f4965590-206b-4f1b-8b58-72d45249e947.png)
![unknown_2](https://user-images.githubusercontent.com/63728326/187063116-5e971c68-960a-4be7-87ab-90c737aac69d.png)

**Comment by Andarix** [comment]
möglich das es an den Änderungen von r10399 liegt

> CODE: Clean up slope handling
> 
> - Use slope_t::flat instead of 0
> - Use if (slope != slope_t::flat) instead of if (slope)
> - Use slope_t::type instead of int/uint8

**Comment by Dwachs** [comment]
sieht eher nach einem Bug wegen Karte-drehen aus.

**Comment by Andarix** [comment]
Die Karte wurde aber nie gedreht. Sie wurde unter Linux erstellt und dann als Serverspiel geladen.

Noch was am Rande. Lade ich die Karte normal, dann kommt trotzdem die Servernachricht, die beim beitreten angezeigt wird. Wusste gar nicht das die inzwischen mit im Spielstand gespeichert wird.

**Comment by Andarix** [comment]
astar.nut Zeile 2473

`            err = command_x.set_slope(b_player, build_hight, ref_hight.get_slope())
`

**Comment by Andarix** [comment]
Seltsam, starte ich die Karte unter Linux mit 4 KIs, dann springen die recht schnell an.

Starte ich die gleiche Karte unter Windows, dann springen KI 1 und 3 (blau und braun) an aber die anderen 2 (gelb und grün) hingegen nicht.

Unter Linux mit r10712 tritt der Slope-Fehler auch auf. Bei Windows konnte ich das noch nicht prüfen.

**Comment by Dwachs** [comment]
Kannst du dir mal die Koordinaten von build_hight, ref_hight ausgeben lassen unmittelbar vor dem set_slope Aufruf?

Wenn die passen, dann ist am Code was faul. Ich braeuchte dann ein Savegame, wo das reproduzierbar auftritt. 

Und deine Skript-Dateien, die github Version passt nicht mehr zu den Zeilennummern.

**Comment by Andarix** [comment]
> Und deine Skript-Dateien, die github Version passt nicht mehr zu den Zeilennummern.

Hab meine lokalen Änderungen gestern committet. Dadurch haben sich die Zeilennummern geändert. Das steht jetzt weiter unten. Das Problem tritt aber auch bei den jetzt aktuellen Dateien auf. An dem Code von den Ausweichstellen wurde da nichts verändert.

Ich muss das auch nochmal als lokales Spiel testen. Möglich, das es am Netzwerkmodus liegt.

[pak64.german 0.123.0.0.5](https://simutrans-germany.com/pak.german/pak64.german_0-123-0-0-5_full.zip)
[1917_448x384_2.sve](https://simutrans-germany.com/files/upload/1917_448x384_2.sve)

**Comment by Andarix** [comment]
Muss am Netzwerkmodus liegen, denn bei einem lokalem Spiel funktioniert es wie es soll

**Comment by Andarix** [comment]
[script-ki_network.sve](https://simutrans-germany.com/files/upload/script-ki_network.sve)
Die Karte steht auf der Stelle, wo etwas später die Ausweichstellen gebaut werden.

lokales Spiel
![Zwischenablage02](https://user-images.githubusercontent.com/63728326/189949939-9fd592a0-cd8a-478a-95db-f6f48e903e8a.png)

Serverspiel
![Zwischenablage01](https://user-images.githubusercontent.com/63728326/189949964-00b94ed5-7a2f-4f83-9f7e-1f0b1cb33d88.png)

**Comment by Dwachs** [comment]
Ja, kann es reproduzieren. Hat es denn im Netzwerkspiel ueberhaupt schon einmal funktioniert??

**Comment by Dwachs** [comment]
behoben mit https://github.com/aburch/simutrans/commit/6908285b8db63030fd2cff65b7eff5b6cee10d6d
