### ISSUE TITLE
Script-KI - Windows vs Linux

### ISSUE THREAD

**Issue by Andarix** [Dwachs/simutrans-scenarios#12]
Es ist eigenartig. Unter Linux verhalten sich die Script-KIs anders als unter Windows.

Gleiche Karte. Unter Linux sind alle 4 KIs aktiv. Unter Windows scheinen 2 KIs sehr träge zu agieren.
Keine Ahnung ob das eventuell mit der Hardware  zu tun haben kann. 

Unter Windows sind mir aber auch schon früher scheinbar inaktive KIs aufgefallen. Als ob die in einer Endlosschleife hängen und nicht weiter wissen.

![script-ki](https://user-images.githubusercontent.com/63728326/190080182-9c241972-ee5f-4920-8009-71b6f6979401.png)

**Comment by Andarix** [comment]
Auch die Verbindungsauswahl scheint unter Linux besser zu funktionieren als unter Windows.

Auf der Windows-Karte sind die beiden Strecken unten in der Mitte vom selben Spieler. Dumm dabei, das es nur die jeweils letzte Verbindung der Industrieketten sind.

![script-ki_routing](https://user-images.githubusercontent.com/63728326/190084013-28d2c093-d89c-4e91-8ee1-657e46ee0125.png)

**Comment by Dwachs** [comment]
Warum da ein Unterschied zwischen Linux und Windows ist -> keine Ahnung.

Die KIs verhalten sich anders, je nachdem ob Spielernummer gerade oder ungerade ist. Siehe factorysearcher_t::work, variable method: ist die =0, dann wird eine Methode benutzt, die der C++ KI nachprogrammiert ist, bei method=1 schaut die KI, wo noch freie Kapazitaeten zu transportieren sind. Allerdings wartet diese dann mindestens einen Monat, bis was passiert. Diese gelb/gruene KIs fangen traeger an, bauen aber unter Umstaenden mehrere Verbindugnen zu einem Abnehmer, was die anderen nicht machen - falls ich mich korrekt erinnere.

**Comment by Andarix** [comment]
Das die KIs untereinander anders arbeiten ist bekannt.

Bei gleicher Codebasis und Karte sollte das Verhalten auf den verschiedenen OS-Systemen aber annähernd gleich oder zumindest ähnlich verlaufen. Das scheint aber offensichtlich nicht der Fall zu sein.

Müsste wohl ein größerer Test mal gemacht werden. Wird aber wohl schwer da wenigstens 10 Leute je OS-System zu finden die es mal testen.
