### ISSUE TITLE
convoi id missing in network game

### ISSUE THREAD

**Issue by Andarix** [Dwachs/simutrans-scenarios#13]
[server13353-network_.sve](https://simutrans-germany.com/files/upload/server13353-network_.sve)
Simutrans r10736
pak64.german 0.123.0.0.5

Als lokales Spiel geladen funktioniert es.

Als Serverspiel geladen kommt ein Fehler das die Konvoi-ID 0 ist.

**Comment by Dwachs** [comment]
Habe dir einen Fix gepusht. 

Problem ist, dass diese Liste sich aendert, wenn zwischendurch ein Convoi geloescht oder erzeugt wird. Der Fix ist, erst eine Kopie der Liste zu machen.

**Comment by Andarix** [comment]
Danke
