### ISSUE TITLE
Rückgabe tile_x.find_object(mo_building)

### ISSUE THREAD

**Issue by Andarix** [Dwachs/simutrans-scenarios#17]
Scheinbar hab ich es geschafft, das Programm total auf Abwege zu bringen.

Eigentlich sollte tile_x.find_object(mo_building) je eine Instanz building_x oder null liefern. Bei mir wird die Koordinate geliefert.
Bin mir nicht sicher ob Spielergebäude einen waytype haben. Da wird -1 geliefert.
Und als Gebäudename wird nur 'Gebaeude' zurück gegeben, statt dem tatsächlichen Namen.

![Screenshot 2023-02-16 125832](https://user-images.githubusercontent.com/63728326/219359245-ef4d734e-6460-45a0-9029-9664123487ad.png)

Bei der anderen Seite der Strecke ähnlicher Effekt. Nur das dort ein Gleis liegt. 

![Screenshot 2023-02-16 130027](https://user-images.githubusercontent.com/63728326/219359738-0496c850-a13e-4094-a057-c813ec985882.png)

[KI-autosave07.sve](https://simutrans-germany.com/files/upload/KI-autosave07.sve)
pak64.german 123.0.0.5
Script-KI Code im Git

Spielstand laden und etwas warten, dann sollte diese Strecke gebaut werden.

**Comment by Dwachs** [comment]
Ich denke, dass ist nur ein Anzeigeproblem. Ist ein Effekt von diesem Commit hier:

https://github.com/aburch/simutrans/commit/0df9a7c37fe464f0b063087fa8bbb86df0ebe8e7

Immer wenn print von einer Instanz aufgerufen wird, wird die _tostring Methode aufgerufen, die gibt hier nur die Koordinaten zurueck. Das kann ich auf jeden Fall verbessern.

get_name gibt nur den Typ zurueck, also Weg, Bruecke, Gebaeude etc. Um den Objektnamen zu bekommen, muss get_desc().get_name() gemacht werden.

Diese Erweiterungsgebaeude sollten einen waytype haben, wie Depots und Stationen. Sehe nicht, wo im Code was schief gehen koennte. Kommt die -1 fuer alle Erweiterungen oder nur fuer bestimmte?

**Comment by Andarix** [comment]
....
> 
> Diese Erweiterungsgebaeude sollten einen waytype haben, wie Depots und Stationen. Sehe nicht, wo im Code was schief gehen koennte. Kommt die -1 fuer alle Erweiterungen oder nur fuer bestimmte?

Das ist ein Dock und keine Erweiterung.

Ich bin da erst drauf gekommen, weil hier ein unnötiges Erweiterungsgebäude gebaut wurde. Das wollte ich unterbinden.

Dabei ist dann aufgefallen, das er am anderen Ende der Strecke das dort notwendige Erweiterungsgebäude nicht mehr baut. Keine Ahnung was er dort als Station erkennt.

Ich hab auch das Gefühl, das das Script schneller läuft als das Programm. Denn die beiden Ausgaben '(1646) ...' dürften gar nicht erscheinen, weil direkt nach der '(1593) ... ' Ausgabe die Pause drin steht.
Das hatte ich schon früher, das Aktionen noch nicht vom Programm beendet worden sinn, aber das Script bereits damit arbeiten will. Gerade nach Bauaktionen. 

Hier fehlt mir die Möglichkeit eine Script-Pause einzulegen.

**Comment by Andarix** [comment]
Mit get_desc() dazwischen kommt der richtige Waytype.

**Comment by Andarix** [comment]
Bei dem Spiel baut Blau eine neue Straßenverbindung vom Chemiewerk. Kurz bevor Maggi die Eisenbahn baut.

Der ursprüngliche Bauplatz ist belegt und am neuen wird keine Startstation gebaut. Keine Ahnung was da schief läuft.

**Comment by Dwachs** [comment]
Wegen pause: das Spiel wird erst in die Pause geschickt, wenn die Kontrolle vom Skript wieder ans Programm geht. Damit das pause-Kommando sofort wirkt, muesste man sleep() direkt hinterher machen. Das ist jetzt nicht so sehr logisch...

**Comment by Dwachs** [comment]
Die Ausgaben von tile_x etc Objekten sollten mit

https://github.com/aburch/simutrans/commit/e21ac8a1bf46cee0387c72a25f9a5f06ba94fc0f

besser aussehen

**Comment by Andarix** [comment]
danke
