### ISSUE TITLE
vehicle_desc_x.get_available_vehicles(wt)

### ISSUE THREAD

**Issue by Andarix** [Dwachs/simutrans-scenarios#19]
Kann es sein, das der Abruf von vehicle_desc_x.get_available_vehicles(wt) auch Fahrzeuge erfasst, die kein Ausführungsdatum haben?

Der Auflieger der hier gewählt wurde wird 1990 eingeführt hat aber keine Ausführung.
[https://www.simutrans-forum.de/mybb/attachment.php?aid=17798](https://www.simutrans-forum.de/mybb/attachment.php?aid=17798)

**Comment by Dwachs** [comment]
Ich verstehe die Frage nicht. Ist Jahr < 1990 sollte dieses Fahrzeug nicht in der Liste drin sein, >=1990 drin sein. 

Was hast du erwartet? und was bekommen?

**Comment by Andarix** [comment]
[Post deutsches Forum und ff](https://www.simutrans-forum.de/mybb/showthread.php?tid=9637&pid=121409#pid121409)

[Lkw Daten Translator](https://makie.de/translator/script/edit.php?obj_id=104788)
[Auflieger Daten Translator](https://makie.de/translator/script/edit.php?obj_id=103869)

**Lkw**: Intro 2.1933 Retire 12.1970
**Auflieger**: Intro 1.1990 Retire keines

In der Fahrzeugreihung stehen die gegeneinander drin. Und beim Lkw wurde der Auflieger angehängt im Jahr 1935 mit Timeline.

Ich vermute jetzt, das die Constraint vom Lkw durchgegangen werden und das erste passende (Fracht) genommen wird, ohne zu prüfen ob es verfügbar ist. Ich nahm bisher an, das die Fahrzeuge zum anhängen von der gleichen Liste stammen die am Anfang abgerufen wird mit der genannten Funktion.

Ich stufe das zwar als Fehler vom pak128.german ein, aber das schließt solche Fehler in anderen Sets nicht aus.

**Comment by Dwachs** [comment]
Ok, hast du das Savegame noch? Der Prototyper sollte den Anhaenger nicht auswaehlen, der Anahenger sollte auch nicht gebaut werden koennen. Das Pakset kann nichts dafuer.

Hast du, waehrend das Spiel laeuft, timeline angeschaltet? Das waere die einzige Moeglichkeit, die ich sehe ... 

Kannst du den Fehler reproduzieren? Vielleicht auf einer Karte, wo nur Holz zu transportieren ist?

**Comment by Dwachs** [comment]
Ok, hast du das Savegame noch? Der Prototyper sollte den Anhaenger nicht auswaehlen, der Anahenger sollte auch nicht gebaut werden koennen. Das Pakset kann nichts dafuer.

Hast du, waehrend das Spiel laeuft, timeline angeschaltet? Das waere die einzige Moeglichkeit, die ich sehe ... 

Kannst du den Fehler reproduzieren? Vielleicht auf einer Karte, wo nur Holz zu transportieren ist?

**Comment by Andarix** [comment]
Save hab ich wahrscheinlich nicht mehr.

Starte einfach ein neues Spiel mit pak128.german v2.1 im Jahr 1936. Gehe zwar davon aus das die Beta v2.2 die gleichen Daten verwendet, hab ich aber noch nicht getestet. Wenn Holz auf der Karte ist, dann sollte auch eine Straßenverbindung gebaut werden. Die Wahrscheinlichkeit für Straße ist recht hoch.

Das ist bei mir recht schnell nach Kartenstart passiert. Habe es bisher nicht weiter verfolgt.

**Comment by Andarix** [comment]
> Ok, hast du das Savegame noch? ...

doch noch gehabt

[p128kg-ki-1936.sve](https://simutrans-germany.com/files/upload/p128kg-ki-1936.sve) ~740 kByte (bis 22. May 2023)

**Comment by Andarix** [comment]
[p128g-1936-512x448-1.sve](https://simutrans-germany.com/files/upload/p128g-1936-512x448-1.sve) ~ 475 kByte ( bis 22. May 2023)

blauer Spieler, um den Monatswechsel zum August werden Lkw LZ6000 und LZ8000 gekauft mit den neuzeitlichen 40 t Aufliegern

**Comment by Dwachs** [comment]
War ein Bug im Programm (mit r10889 behoben) und im Skript. Habe dir einen Fix gepusht.

https://github.com/Dwachs/simutrans-scenarios/commit/36ebfde2ca959994fe66396f29a25bc6e23d3f11

**Comment by Andarix** [comment]
funktioniert

Danke
