### ISSUE TITLE
Query graphic set

### ISSUE THREAD

**Issue by Andarix** [Dwachs/simutrans-scenarios#2]
[de]Die Abfrage des laufenden Grafiksets ermöglicht Anpassungen an das jeweilige Grafikset.[/de]

The query of the running graphics set enables adjustments to be made to the respective graphics set.

**Comment by Dwachs** [comment]
Man koennte die copyright-info aus ground.outside.pak nehmen. Wuerde das reichen? Verzeichnisname duerfte nicht so hilfreich sein.

**Comment by Andarix** [comment]
Sicher reicht das.
