### ISSUE TITLE
Get version number and revision of simutrans

### ISSUE THREAD

**Issue by Yona-TYT** [Dwachs/simutrans-scenarios#4]
I would like to be able to check if the version of simutrans is compatible with my script, for that I need to know the version or the revision of simutrans (it would be great to get both) ... greetings !.

**Comment by Dwachs** [comment]
I think you can assume that the executable is more recent than the script. If the script is more recent then the user should download a new simutrans version. What do you think?

**Comment by Yona-TYT** [comment]
> I think you can assume that the executable is more recent than the script. If the script is more recent then the user should download a new simutrans version. What do you think?

Certainly, even so I would like to advise from the script about this, there must still be players using old versions of simutrans.

On the other hand, thanks to the fact that it is now possible to obtain the name of the pakset, I would like to show a warning of compatibility with paksets and at the same time check if the version / revision of simutrans is compatible.

**Comment by Yona-TYT** [comment]
![Example-tyt](https://user-images.githubusercontent.com/27737574/127162964-0b65c231-c41f-4ddd-a5b3-080f8374f9df.png)
I leave you an example of how I would like to use this .

**Comment by Andarix** [comment]
add r9983 I think

**Comment by Dwachs** [comment]
implemented https://github.com/aburch/simutrans/commit/c1fbbf179181ad864bf588e341c74ccbb3abdf7e#diff-753497ebe1a97c5defa0ef27b8319ac1080986b92b271a945f588a7d291f9184
