### ISSUE TITLE
building_desc_x.get_available_stations() 

### ISSUE THREAD

**Issue by Andarix** [Dwachs/simutrans-scenarios#7]
[http://dwachs.github.io/simutrans-sqapi-doc/classbuilding__desc__x.html#a336c50072747b70fb74273b5a5268702](http://dwachs.github.io/simutrans-sqapi-doc/classbuilding__desc__x.html#a336c50072747b70fb74273b5a5268702)

> **freight**	station should accept this freight (**_if null then return all buildings_**)

`stations_list = building_desc_x.get_available_stations(building_desc_x.station, wt, good)`

good is null

The script returns an error message:
> Error: [parameter 3 has an invalid type 'null' ; expected: 'table|class|instance']

**EDIT**
script tool section

**Comment by Dwachs** [comment]
good has to be set to an empty table
`building_desc_x.get_available_stations(building_desc_x.station, wt, {})`
