### ISSUE TITLE
station raw name have problems

### ISSUE THREAD

**Issue by Andarix** [Dwachs/simutrans-scenarios#8]
Digits and _ are not correctly recognized in station object names.

good is _good_desc_x("none")_ ( [null does not work for all stations](https://github.com/Dwachs/simutrans-scenarios/issues/7) )

_obj_name_ is the station name to search -> bridge_stations[]
_station_obj_ is the return value

```
  stations_list = building_desc_x.get_available_stations(building_desc_x.station, wt, good)
  foreach(o in stations_list) {
       if (o.get_name() == obj_name) {
         station_obj = o
         break
       }
  }

``` 

>  station_obj PSFreightTrainStop
>   bridge_stations[1] PSFreightTrainStop

>   station_obj FreightTrainStop
>   bridge_stations[0] FreightTrainStop

>   station_obj null: null
>   bridge_stations[1] Station_MK_VIb

>   station_obj null: null
>   bridge_stations[0] Station_MK_VIa

>   station_obj FreightTrainStop
>   bridge_stations[1] FreightTrainStop

>   station_obj null: null
>   bridge_stations[0] MHz1FreightTrainStop

**EDIT**
script tool section

**Comment by Dwachs** [comment]
Could it be that at the time the script runs, some of the stations are not available anymore (out of timeline)?

**Comment by Andarix** [comment]
All stations are available.

I built it and immediately applied the tool afterwards.

**Comment by Dwachs** [comment]
Can you please send me the script?

**Comment by Andarix** [comment]
PM int. forum

**Comment by Andarix** [comment]
sorry, the problem is not the names but the selection of good
