### ISSUE TITLE
problem by Script tool cursor

### ISSUE THREAD

**Issue by Andarix** [Dwachs/simutrans-scenarios#9]
I have to cursors _**script_tool_pass_waiting**_  and _**script_tool_pass_waiting_80**_ .

Load the game, then cursor _**script_tool_pass_waiting_80**_ overwrite the cursor _**script_tool_pass_waiting**_ .

So the tool that defined the button and cursor _**script_tool_pass_waiting**_ displays the button and cursor _**script_tool_pass_waiting_80**_.

If a cursor contains the name of another cursor as part of the name, the cursor with the name is overwritten by the longer name.

**Comment by Dwachs** [comment]
It seems that this is a very old: it is also used to read icon names in menuconf.tab.
